### PR TITLE
removed unused code from api file

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

refactored all API calls to an API context so removed all the unused code

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.
- [x] This is part of a refactor.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [x] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Refactor front end to use context state management](https://trello.com/c/yjQJ6oKC/17-refactor-front-end-to-use-context-state-management)

**Review by timotheemcdonald — APPROVED** [review]
Glad you're removing this unused code, it will reduce technical debt going forward!

**Review by jessicagertig — CHANGES_REQUESTED** [review]
Everything looks good and is working when I pull your branch down.  However, before we merge your branch, it would be best practice for you to git pull the changes to main to your branch and commit them.  (Tim's PR 29 was merged after you opened this pull request).

**Comment by JessBonanno** [comment]
I pulled main down to this branch and tried to commit but it looks like I already have the changes here.  I'm getting a message that there is no changes to commit.

**Review by jessicagertig — APPROVED** [review]
Look great! I pulled it down and tested the app and all is working as it was before.

**Pull request merged**
