### PR TITLE
fix(groomer profile update bug)

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

the groomer profile would not update to reflect edits until hard refresh, this issue has been
resolved

## Type ##

- [x] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[groomer profile should display changes on update without hard refresh](https://trello.com/c/qP4zWFgh/47-groomer-profile-should-display-changes-on-update-without-hard-refresh)

**Review by timotheemcdonald — APPROVED** [review]
Good bug squashing skills!

**Review by waveownage — APPROVED** [review]
Great work on making the profile update reflect changes without manually refreshing page.

**Review by jessicagertig — APPROVED** [review]
This looks really clean. I pulled the branch down and now the groomer profile updates without a hard refresh.

**Pull request merged**
