### PR TITLE
Testing/landing nav login

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

Created tests using cypress for 
- landing page 
- login page 
- navigation

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.
- [x] This is tests.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Create tests for the front end components](https://trello.com/c/qJJ3Pjb8/70-create-tests-for-the-front-end-components)

**Review by timotheemcdonald — DISMISSED** [review]
All tests pass on my end

**Review by waveownage — DISMISSED** [review]
pulled and working locally. All 3 test passing LoadingComponent, NotFoundPage, & LoginContainer

**Review by waveownage — APPROVED** [review]
still working locally and all test passing

**Review by timotheemcdonald — APPROVED** [review]
tests still pass on my end, approved!

**Pull request merged**
