### PR TITLE
Nav Bar and Groomer Side Nav.

### PR DESCRIPTION
**Pull request by ShawnBatson**
## Description ##

This is the pull request for the Site-Wide Nav Bar, and also the pop-out specialized groomer Nav Bar, bare bones sans-design. 

## Type ##

- [ ] This is a bugfix.
- [x] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [ ] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by ShawnBatson** [comment]
[Site wide navigation bar once logged in for Groomer](https://trello.com/c/3u8heD0Q/51-site-wide-navigation-bar-once-logged-in-for-groomer)

**Comment by ShawnBatson** [comment]
[Site wide navigation bar once logged in for Pet Owner.](https://trello.com/c/B4CeCbkT/52-site-wide-navigation-bar-once-logged-in-for-pet-owner)

**Comment by ShawnBatson** [comment]
[Navigation for non-logged in users.](https://trello.com/c/BINT3mdb/53-navigation-for-non-logged-in-users)

**Review by jessicagertig — CHANGES_REQUESTED** [review]
Great job getting us started on the navigation Shawn.   I appreciate the commenting very much.  I did notice in nav.css that there is commented out code from line 15 to 20, I'd like to request you remove the commented out code.

**Review by jessicagertig — APPROVED** [review]
Great!  Thanks for removing that!

**Review by Broast42 — APPROVED** [review]
Really like the custom pop-out menu and I'm really glad you got rid of the yellow. Nothing against yellow it just really clashed. Great Job.

**Pull request merged**
