### PR TITLE
Refactor customer form

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

The customer profile form has been refactored to match the pet-form.
- Form is more user friendly on opening and closing
- Loading view added on submission
- Message that informed user of the update now on a timer and disappears rather than persisting

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.
- [x] This is part of a refactor.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [x] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Refactor customer and groomer update profile forms to match the pet profile form once done](https://trello.com/c/rJIZfB7b/49-refactor-customer-and-groomer-update-profile-forms-to-match-the-pet-profile-form-once-done)

**Comment by JessBonanno** [comment]
There may be merge conflicts when pet-form is merged because I had to add similar state to FormContext.  It should be an easy resolution when the time comes.  I can also handle it after pet form is merged and before this is merged by pulling pet-form into this branch locally.

**Comment by JessBonanno** [comment]
[Refactor customer and groomer update profile forms to match the pet profile form once done](https://trello.com/c/rJIZfB7b/49-refactor-customer-and-groomer-update-profile-forms-to-match-the-pet-profile-form-once-done)

**Review by timotheemcdonald — DISMISSED** [review]
No errors, No warnings, nice clean refactor. Good job thanks for this!

**Comment by JessBonanno** [comment]
I've pulled the latest changes from the last merge into main and handled any conflicts.  This branch should be merged before I can do the same for the groomer form PR branch.

**Review by jessicagertig — APPROVED** [review]
I pulled this branch down and the customer form is working.  The UI is much better.  I was able to edit the customer's name.  The code looks nice and clean.

**Review by timotheemcdonald — APPROVED** [review]
pulled it down and no errors or warnings, looks good

**Pull request merged**
