### PR TITLE
Feature/responsive

### PR DESCRIPTION
**Pull request by timotheemcdonald**
## Description ##

Removed images on Mobile width for better loading times, text and text sections responsive to phone-width

## Type ##

- [ ] This is a bugfix.
- [x] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [ ] Have you linked this pull request to a Trello card?
- [ ] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Review by JessBonanno — APPROVED** [review]
Mobile styles are looking good, great work.  Pulled locally and no warnings in console.

**Review by waveownage — APPROVED** [review]
looks good

**Comment by jessicagertig** [comment]
Closing because Test and publish coverage is stalled and it will not allow the workflow to be reinitiated.

**Comment by waveownage** [comment]
closed because : Test and publish test coverage Expected — Waiting for status to be reported

**Pull request merged**
