### PR TITLE
Feature/landing iii

### PR DESCRIPTION
**Pull request by timotheemcdonald**
## Description ##

Added two sections here, one for more information on the App and one for information for Groomers.

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [ ] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Review by JessBonanno — DISMISSED** [review]
Looking great Tim.  Code is clear and readable. No warnings in my console when pulled and run locally.

**Review by jessicagertig — DISMISSED** [review]

**Comment by jessicagertig** [comment]
I missed submitting my comment before approving.  I pulled this down locally and everything worked and I got no additional warnings.  Looking good!

**Review by jessicagertig — APPROVED** [review]
Still looks good and works properly when the branch is pulled down locally.

**Review by JessBonanno — APPROVED** [review]
everything working on my end after pulling this branch locally.  Good work Tim

**Pull request merged**
