### PR TITLE
Create pet form

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

Creating form for customers to enter pet information to the database

## Type ##

- [ ] This is a bugfix.
- [x] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Review by timotheemcdonald — DISMISSED** [review]
This is great, making good progress.

**Comment by JessBonanno** [comment]
[Create a form component for adding individual pets.](https://trello.com/c/K1wuiWD7/22-create-a-form-component-for-adding-individual-pets)

**Comment by JessBonanno** [comment]
[Form validation for add pet profile form to ensure necessary information is added and in some case in the correct format](https://trello.com/c/Atg8i2QD/24-form-validation-for-add-pet-profile-form-to-ensure-necessary-information-is-added-and-in-some-case-in-the-correct-format)

**Review by timotheemcdonald — COMMENTED** [review]
Looks good I'm not seeing any errors here nice refactor

**Review by timotheemcdonald — APPROVED** [review]
Did a git fetch and it looks good

**Review by jessicagertig — APPROVED** [review]
The form looks great. It posts to the backend.  The UI looks nice.  Thanks for doing the package-lock.

**Pull request merged**
