### PR TITLE
Removed Storybook

### PR DESCRIPTION
**Pull request by jessicagertig**
## Description ##

Our team has agreed we will not be using storybook, since previously a good number of components and devdependencies were added (in addition to those originally in the scaffolding) storybook, it's components, and it's devdependencies have been removed to create a lighter app.  This significantly altered package-lock.json.  After this pull request is merged, it might be a good idea to delete your node-modules and package-lock file and then do npm install.

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.
- [x] This is a refactor.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing OR refactor/describe_refactor

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by jessicagertig** [comment]
I am going to close this pull request for the time being in order to discuss with a team member.

**Comment by jessicagertig** [comment]
Issue resolved.  Please review this pull request.

**Review by timotheemcdonald — DISMISSED** [review]
Thanks for doing this! It will make the App much more efficient and will run faster.

**Review by JessBonanno — APPROVED** [review]
Thanks for cleaning up the app!  No issues when I pulled locally

**Review by timotheemcdonald — APPROVED** [review]
Did a git fetch and not seeing any errors or warnings.
Approved.

**Pull request merged**
