### PR TITLE
initial project setup and Context API scaffold

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description #

added .idea to .gitignore, created context files, wrapped app in the context RootProvider

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.
- [x] This is part of a refactor.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [x] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Refactor front end to use context state management](https://trello.com/c/yjQJ6oKC/17-refactor-front-end-to-use-context-state-management)

**Comment by JessBonanno** [comment]
I notice that I did not manually change anything in my package-lock.json but it reflects 24k lines of code removed.  My local version is working properly but it would be helpful if someone else could pull this branch locally to confirm it is working for them as well.

**Review by timotheemcdonald — APPROVED** [review]
This looks good, thanks for working late last night on this!

**Review by jessicagertig — APPROVED** [review]
Looks good!  It will be great to get the components cleaned up with logic abstracted into context.  I pulled this branch down to my local environment and logged in as both a groomer and a customer and all is working as it did before.  

Just a note, look out for the package-lock.json in the future and don't commit it.  Ideally if changes are made to it we will make a separate pull request for that so everyone can coordinate their lock files.

**Comment by JessBonanno** [comment]
Thanks, I will abstract as much of the logic out to context as possible.

**Pull request merged**
