### PR TITLE
Feature/image uploading

### PR DESCRIPTION
**Pull request by JessBonanno**
## Image upload components

- Components in place to allow uploading of pet image and pet vaccination image once we have ways to display individual pets
- Uploading of groomer license now available from groomer info tab

## Type ##

- [ ] This is a bugfix.
- [x] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Create a form component uploading pet's photos](https://trello.com/c/u6l8Aft7/51-create-a-form-component-uploading-pets-photos)

**Comment by JessBonanno** [comment]
[photo upload component ( 3rd party api )](https://trello.com/c/H9hjBBIp/26-photo-upload-component-3rd-party-api)

**Comment by JessBonanno** [comment]
[Add functionality to upload photos.](https://trello.com/c/yyJstjNZ/43-add-functionality-to-upload-photos)

**Review by trevorjamesmartin — APPROVED** [review]
good code comments

**Review by timotheemcdonald — APPROVED** [review]
Approved, excited to try and connect this to the pet profile display.

**Pull request merged**
