### PR TITLE
fix(after login): fixed routing after login

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

- refactored landing route to '/info'
- added a blank page for '/'
- after logging in okta pushes to '/' so on this page I added logic to check userRole, if groomer or customer the app will push to respective dashboard route
- if no userRole(not logged in) it will push to '/info' (landing page)
- refactored navigation to replace home with info and removed double dashboard link
- made the logo clickable to '/info'

## Type ##

- [x] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[BUG: The groomer info does not load on up initial render, only after something triggers re render](https://trello.com/c/TyTymM6d/66-bug-the-groomer-info-does-not-load-on-up-initial-render-only-after-something-triggers-re-render)

**Review by timotheemcdonald — DISMISSED** [review]
This is MUCH cleaner and a great quality of life fix!

**Review by waveownage — APPROVED** [review]
Pulled and working locally. Groomer login now routing to groomer dashboard after login and customer login now routing to customer dashboard after login.

**Review by timotheemcdonald — APPROVED** [review]
Still looks good on my end, no errors!

**Pull request merged**
