### PR TITLE
refactor(groomer form):

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

 moved groomer form buttons to the newly created groomer dashboard to match the customer dashboard

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.
- [x] This is part of a refactor.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Refactor groomer form buttons to match the way they appear on the customer dashboard](https://trello.com/c/dSwHCajZ/63-refactor-groomer-form-buttons-to-match-the-way-they-appear-on-the-customer-dashboard)

**Comment by JessBonanno** [comment]
[Refactor groomer form buttons to match the way they appear on the customer dashboard](https://trello.com/c/dSwHCajZ/63-refactor-groomer-form-buttons-to-match-the-way-they-appear-on-the-customer-dashboard)

**Review by timotheemcdonald — APPROVED** [review]
Pulled down and it's working well on my end, Approved.

**Review by waveownage — APPROVED** [review]
Pulled locally and works!

**Pull request merged**
