### PR TITLE
Initializing Landing Page

### PR DESCRIPTION
**Pull request by timotheemcdonald**
## Description ##

- Created the Landing Page File, currently blank
- Reworked the Navigation and Routing to differentiate between Dashboard & Home, Home was previously directing to Dashboard
- If we decide to implement a new Dashboard I can go back in and differentiate between Dashboard & Profile Pages
- Will work on styling once this is up

## Type ##

- [ ] This is a bugfix.
- [ x] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [ ] Have you linked this pull request to a Trello card?
- [ ] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [ ] Is this ready to be reviewed?
- [ ] Have you added two reviewers to this pull request?

### CODE REVIEW

**Review by JessBonanno — CHANGES_REQUESTED** [review]
I am getting a warning in my console after running the branch locally

"./src/components/pages/Landing/LandingContainer.js
  Line 2:8:  'styled' is defined but never used  no-unused-vars"
  
I would also suggest naming your branches according to the convention going forward,  for example, this branch should be feature/landing-page

Other than that the code looks good from what I see.

**Review by JessBonanno — APPROVED** [review]
Thanks for handling that error, looks great!

**Review by jessicagertig — APPROVED** [review]
I pulled the branch down.  The scaffolding looks good.  We will take care of the bug where the Okta Login Widget crashes after the Home button and the Login button are clicked back and forth alternatively through an error page or redirect since it's an issue with Okta we can't fix.  The ticket has been added to Trello.

**Comment by jessicagertig** [comment]
After pull request 30 was merged, a small conflict was created in the navigation bar which I resolved.

**Comment by jessicagertig** [comment]
AWS Previews did go through per AWS.

**Comment by jessicagertig** [comment]
[Landing Page](https://trello.com/c/yKLWLgKN/21-landing-page)

**Pull request merged**
