### PR TITLE
refactor(customer profile) to remove the welcome message

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

The welcome message on the customer profile was no longer needed after the implementation of the dashboard so it was removed.

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.
- [x] This is a refactor.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Remove the welcome messages on the profile info that's displayed on the dashboards](https://trello.com/c/PKPQuNuN/64-remove-the-welcome-messages-on-the-profile-info-thats-displayed-on-the-dashboards)

**Review by timotheemcdonald — DISMISSED** [review]
This was a great QOL improvement, thanks for catching it.

**Review by timotheemcdonald — APPROVED** [review]
This makes it much cleaner, thanks!

**Review by waveownage — APPROVED** [review]
Branch pulled and is working locally on my end. Welcome message no longer in customer profile.

**Pull request merged**
