### PR TITLE
Feature/groomer search

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

Created map to display all groomers locations, when clicked a popup appears with basic info and a button linking to the groomer profile page.  
- There is a warning in the console that you can't perform a state change on unmounted component but I was unable to find a way around this and still have the button work.  This is because on clicking the button the map thinks its closing the popup and trying to reset the selected groomer back to null.  I had to set a timeout before it sets the groomer back to null and so we get the warning.  Everything works as expected though.

## Type ##

- [ ] This is a bugfix.
- [x] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Connect Map Box API to the enhanced groomer search](https://trello.com/c/opYZcfvn/30-connect-map-box-api-to-the-enhanced-groomer-search)

**Comment by JessBonanno** [comment]
[Connect Map Box API to the enhanced groomer search](https://trello.com/c/opYZcfvn/30-connect-map-box-api-to-the-enhanced-groomer-search)

**Review by timotheemcdonald — APPROVED** [review]
Search Function works and Map Box shows on my end, FE & BE connected

**Review by jessicagertig — APPROVED** [review]
I pulled down this branch and tested it, and other than the warning already mentioned in the PR description, no additional warnings are created and it's working with the backend as intended.   This remained true after merging in the latest version of main, which was the groomer-dashboard component (the source of the undefined vars warnings).

**Pull request merged**
