### PR TITLE
groomer info now displays hours of operation

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

The hours of operation are now displayed in the groomer info panel of the groomer dashboard
- we may want to consider restyling this to allow more room for the items.

## Type ##

- [ ] This is a bugfix.
- [x] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [ ] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Create a component to display groomers available hours in Groomer Dashboard](https://trello.com/c/aHJITBSO/60-create-a-component-to-display-groomers-available-hours-in-groomer-dashboard)

**Review by timotheemcdonald — DISMISSED** [review]
This looks good I'm not seeing any errors or warnings.

**Review by waveownage — DISMISSED** [review]
Hours of operation are now showing on groomer dashboard - my info. Pulled locally and working!

**Review by waveownage — APPROVED** [review]
pulled locally and works

**Review by timotheemcdonald — APPROVED** [review]
Working for me now! Approved

**Pull request merged**
