### PR TITLE
Calculate latitude and longitude from groomer address

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

The groomers latitude and longitude will be calculated and added to the database on update or adding of an address.

## Type ##

- [ ] This is a bugfix.
- [x] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Handle creating latitude and longitude from address when creating a new groomer or updating address](https://trello.com/c/EZAPFeCr/62-handle-creating-latitude-and-longitude-from-address-when-creating-a-new-groomer-or-updating-address)

**Review by timotheemcdonald — COMMENTED** [review]
I am not seeing the Lat/Long on my end, but I'm not sure if this is just setting it up to display it later or not.

**Review by timotheemcdonald — APPROVED** [review]
This looks good to me, I'm seeing two warnings in the console about declared variables that are defined but never used - but this isn't a big deal and may be used in other merges so I will approve.

**Review by waveownage — APPROVED** [review]
Pulled and works locally on my end.

**Pull request merged**
