### PR TITLE
fix groomer info not displaying on initial render

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

Groomer info now properly displaying on initial render.  useEffect needed to be added to call to the API on render for the info.

## Type ##

- [x] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[BUG: The groomer info does not load on up initial render, only after something triggers re render](https://trello.com/c/TyTymM6d/66-bug-the-groomer-info-does-not-load-on-up-initial-render-only-after-something-triggers-re-render)

**Review by timotheemcdonald — DISMISSED** [review]
Looks Good to me

**Review by waveownage — APPROVED** [review]
Pulled and working locally. Groomer info is now displaying initially.

**Review by timotheemcdonald — APPROVED** [review]
Pulled down and no errors

**Pull request merged**
