### PR TITLE
Refactor/context

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

Fully refactored local state to use Context API, no breaking changes.

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.
- [x] This is a refactor.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Refactor front end to use context state management](https://trello.com/c/yjQJ6oKC/17-refactor-front-end-to-use-context-state-management)

**Review by timotheemcdonald — DISMISSED** [review]

**Review by jessicagertig — COMMENTED** [review]
You can go ahead and delete the apiUrl variable from the api file. Also the example data function.

**Review by jessicagertig — APPROVED** [review]
I see you were ahead of me in deleting the variable.  The refactor looks really good.  Great work.

**Review by timotheemcdonald — APPROVED** [review]
Looks good, I like how you refactored the state management system here.
Thank you for doing the refactoring!

**Pull request merged**
