### PR TITLE
Home and Navigation refactored to use Context API

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

Home component and nav component have been refactored to use context now instead of useState

## Type ##

- [ ] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.
- [x] This is part of a refactor.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [x] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Refactor front end to use context state management](https://trello.com/c/yjQJ6oKC/17-refactor-front-end-to-use-context-state-management)

**Review by timotheemcdonald — DISMISSED** [review]
This looks good, but there's a warning on GitHub saying there's an error on line 41&44:
_React Hook useEffect has missing dependencies: 'getUserID', 'setUserInfo', and 'setUserRole'. Either include them or remove the dependency array_
Probably a result of the refactor but wanted to mention it.

**Comment by JessBonanno** [comment]
> This looks good, but there's a warning on GitHub saying there's an error on line 41&44:
> _React Hook useEffect has missing dependencies: 'getUserID', 'setUserInfo', and 'setUserRole'. Either include them or remove the dependency array_
> Probably a result of the refactor but wanted to mention it.

I handled the unused deps issue, good catch!

**Comment by JessBonanno** [comment]
On further examination those deps need to be left out of the dep array in the useEffects or else it endlessly hits the API so I added the eslint ignore comments above them to clear the console warnings.

**Review by NV1028 — COMMENTED** [review]
Code works on my machine 
No errors in console

**Review by NV1028 — DISMISSED** [review]
Resubmitting with Approve checked
I pulled this branch down and it works on my local env.

**Review by jessicagertig — COMMENTED** [review]
I believe you can now remove the eslint-disable-next line in both files.

**Review by NV1028 — APPROVED** [review]

**Review by NV1028 — DISMISSED** [review]
2 lines of commented code removed.  No problems.

**Review by jessicagertig — APPROVED** [review]
Thank you for taking care of the eslint disable lines.  This branch works on my local environment.

**Review by NV1028 — APPROVED** [review]
Works on my machine no problems.

**Pull request merged**
