### PR TITLE
feature/customer-dashboard-component

### PR DESCRIPTION
**Pull request by waveownage**
## Description ##

Added customer dashboard, overview, and tabs component. Linked customer dashboard to navbar under dashboard. Fontawesome script added to index.html. Deleted radio variable (not used) and updated class to className for the pawprint Icons.

## Type ##

- [ ] This is a bugfix.
- [x] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [ ] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [ ] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by jessicagertig** [comment]
[Customer Dashboard component](https://trello.com/c/26siXcaM/32-customer-dashboard-component)

**Review by JessBonanno — DISMISSED** [review]
Just reminder for your next branch while working on this feature to handle this warning since still a work in progress.  Pulled branch locally and looks good.

'Radio' is defined but never used

**Review by jessicagertig — CHANGES_REQUESTED** [review]
Everything is looking really good!  The tab component moves nicely.  The only thing I noticed is that 'class' is used instead of 'className' as my browser threw up a warning for that.  So if you could change all the instances of 'class' to 'className' that would be great.

**Review by JessBonanno — APPROVED** [review]
The code looks good.  When I ran it locally I noticed when switching to the search groomers tab the divider jumps out a bit.  Maybe look into making all the tabs the same width to avoid this in a future commit.

**Review by jessicagertig — APPROVED** [review]
Thanks for the changes.  I see what Jess was referring to, the horizontal width of the tab section increases when you select search groomers, something to look into with the styling.  Also I noted that now we have two dashboard links in the navbar for the customer, I'm sure the old components need to be sorted out, but it's something to keep in mind.  Looking good though!

**Pull request merged**
